### PR TITLE
Remove copied API client, instead use deno-slack-api client.

### PR DESCRIPTION
**Pull request by filmaj**

### CODE REVIEW

**Review by shapirone — APPROVED** [review]
LGTM 🥳 

Added Curtis as a reviewer in case there is anything he wants to check for lambda purposes

**Review by curtisallen — APPROVED** [review]
nice LGTM. Tangentially I wonder if we should add a `deps.ts` file with all of our imports, making it easier to update them as needed. https://deno.land/manual@v1.20.4/examples/manage_dependencies

**Comment by filmaj** [comment]
Great call @curtisallen, I will add that to this PR, and then merge in.

**Comment by filmaj** [comment]
Actually, I will send usage of `deps.ts` and `dev_deps.ts` as a separate PR, if only to narrow the scope of PRs down in case that is useful for future referencing/educational purposes. Merging this in!

**Pull request merged**
